export const products = [
  {
    name: 'Laptop',
    manufacturer: 'Lenovo',
    description: 'Very fast',
    price: 5000,
    image: 'laptop.jpg',
  },
  {
    name: 'Mouse',
    manufacturer: 'Logitech',
    description: 'Really comfortable',
    price: 300,
    image: 'mouse.jpg',
  },
  {
    name: 'Keyboard',
    manufacturer: 'Logitech',
    description: 'Quiet switches',
    price: 500,
    image: 'keyboard.png',
  },
  {
    name: 'Printer',
    manufacturer: 'Dell',
    description: 'Very quiet',
    price: 800,
    image: 'printer.jpg',
  },
  {
    name: 'PC',
    manufacturer: 'Lenovo',
    description: 'Fast gaming PC',
    price: 10000,
    image: 'pc.jpg',
  },
  {
    name: 'Headphones',
    manufacturer: 'HyperX',
    description: 'Good sound',
    price: 400,
    image: 'headphones.jpg',
  },
  {
    name: 'Monitor',
    manufacturer: 'Dell',
    description: 'High refresh rate',
    price: 1200,
    image: 'monitor.jpg',
  },
  {
    name: 'Webcam',
    manufacturer: 'Logitech',
    description: '1080p resolution',
    price: 250,
    image: 'webcam.jpg',
  },
  {
    name: 'Gaming Chair',
    manufacturer: 'Secretlab',
    description: 'Ergonomic and stylish',
    price: 350,
    image: 'chair.jpg',
  },
  {
    name: 'External SSD',
    manufacturer: 'Samsung',
    description: 'Blazing fast storage',
    price: 700,
  },
  {
    name: 'Docking Station',
    manufacturer: 'Dell',
    description: 'Multiple ports for connectivity',
    price: 900,
  },
  {
    name: 'Tablet',
    manufacturer: 'Lenovo',
    description: 'Lightweight and fast',
    price: 1200,
  },
  {
    name: 'Speakers',
    manufacturer: 'HyperX',
    description: 'Immersive audio',
    price: 600,
  },
  {
    name: 'Graphics Card',
    manufacturer: 'NVIDIA',
    description: 'High-end performance',
    price: 2500,
  },
  {
    name: 'Router',
    manufacturer: 'TP-Link',
    description: 'Wi-Fi 6, ultra-fast',
    price: 320,
  },
];
